version: 0.2

phases:
  install:
    commands:
      - echo "Installing packages from requirements.txt..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Fetching secrets from AWS Secrets Manager..."
      - export SECRET=$(aws secretsmanager get-secret-value --secret-id <SECRET_NAME> --query SecretString --output text)
      - export SECRET_KEY=$(echo $SECRET | jq -r .SECRET_KEY)
      - export NAME=$(echo $SECRET | jq -r .NAME)
      - export USER=$(echo $SECRET | jq -r .USER)
      - export PASSWORD=$(echo $SECRET | jq -r .PASSWORD)
      - export HOST=$(echo $SECRET | jq -r .HOST)
      - echo "Environment variables exported successfully."

  build:
    commands:
      - echo "Running migrations..."
      - python manage.py migrate --noinput
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
